#!/bin/bash

#Display weekdays
#i=1
#for day in Mon Tue Wed Thu Fri; do
#echo "Weekdays : $((i++)) : " ${day}
#done
#---------
#Delete 5 files
#for i in {1..5}; do
# rm ${i}
#done
#--------------------
#Create 5 files
#for i in {1..5};do
#  echo "files created : "  ${i}
#   touch $i
#   done
#   ls -ltr
#----------------------
#List all users one by one in /etc/passwd file
#i=1
#for user in `awk -F: '{print $1}' /etc/passwd`; do
#  echo "user $((i++))"  $user
#  done
#-----------------

# do while loop
c=1
while [ $c -le 5 ]
do
        echo "Welcone $c times"
        (( c++ ))
done













